/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "surface-container": "#161a21",
        "outline-variant": "#45484f",
        "tertiary-container": "#fa53a4",
        "on-tertiary": "#4b002a",
        "tertiary": "#ff6daf",
        "on-error-container": "#ffb2b9",
        "surface-tint": "#bd9dff",
        "surface-variant": "#22262f",
        "on-surface-variant": "#a9abb3",
        "background": "#0b0e14",
        "on-error": "#490013",
        "on-primary-container": "#2e006c",
        "on-surface": "#ecedf6",
        "surface-dim": "#0b0e14",
        "secondary-fixed": "#65e1ff",
        "surface-container-low": "#10131a",
        "on-primary": "#3c0089",
        "error-dim": "#d73357",
        "surface": "#0b0e14",
        "primary-fixed-dim": "#a67aff",
        "secondary": "#53ddfc",
        "tertiary-fixed-dim": "#ff73b1",
        "inverse-primary": "#742fe5",
        "primary-container": "#b28cff",
        "primary": "#bd9dff",
        "secondary-container": "#00687a",
        "inverse-surface": "#f9f9ff",
        "tertiary-fixed": "#ff8cbc",
        "on-secondary-container": "#ecfaff",
        "secondary-dim": "#40ceed",
        "on-tertiary-container": "#2f0018",
        "primary-dim": "#8a4cfc",
        "on-primary-fixed": "#000000",
        "on-secondary-fixed-variant": "#005969",
        "outline": "#73757d",
        "error": "#ff6e84",
        "surface-container-high": "#1c2028",
        "surface-bright": "#282c36",
        "on-primary-fixed-variant": "#390083",
        "secondary-fixed-dim": "#48d4f3",
        "on-secondary-fixed": "#003a45",
        "on-tertiary-fixed-variant": "#740044",
        "inverse-on-surface": "#52555c",
        "on-secondary": "#004b58",
        "on-tertiary-fixed": "#37001d",
        "on-background": "#ecedf6",
        "primary-fixed": "#b28cff",
        "tertiary-dim": "#ff67ad",
        "error-container": "#a70138",
        "surface-container-highest": "#22262f",
        "surface-container-lowest": "#000000"
      },
      fontFamily: {
        "headline": ["Manrope"],
        "body": ["Inter"],
        "label": ["Inter"]
      },
      borderRadius: {
        "DEFAULT": "1rem",
        "lg": "2rem",
        "xl": "3rem",
        "full": "9999px"
      },
    },
  },
  plugins: [],
}
