/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "surface-container": "#fff0f7",
        "outline-variant": "#e3b9d1",
        "tertiary-container": "#fa53a4",
        "on-tertiary": "#4b002a",
        "tertiary": "#ff6daf",
        "on-error-container": "#ffb2b9",
        "surface-tint": "#bd9dff",
        "surface-variant": "#fde6f2",
        "on-surface-variant": "#5a3e7a",
        "background": "#fff5f8",
        "on-error": "#490013",
        "on-primary-container": "#4a2c6d",
        "on-surface": "#4a2c6d",
        "surface-dim": "#fff5f8",
        "secondary-fixed": "#65e1ff",
        "surface-container-low": "#fff7fb",
        "on-primary": "#ffffff",
        "error-dim": "#d73357",
        "surface": "#fff5f8",
        "primary-fixed-dim": "#b47bff",
        "secondary": "#86d8ff",
        "tertiary-fixed-dim": "#ff73b1",
        "inverse-primary": "#742fe5",
        "primary-container": "#b28cff",
        "primary": "#b47bff",
        "secondary-container": "#00687a",
        "inverse-surface": "#f9f9ff",
        "tertiary-fixed": "#ff8cbc",
        "on-secondary-container": "#ecfaff",
        "secondary-dim": "#53ddfc",
        "on-tertiary-container": "#2f0018",
        "primary-dim": "#9b5cff",
        "on-primary-fixed": "#000000",
        "on-secondary-fixed-variant": "#005969",
        "outline": "#d4a6c4",
        "error": "#ff6e84",
        "surface-container-high": "#ffe9f3",
        "surface-bright": "#ffffff",
        "on-primary-fixed-variant": "#390083",
        "secondary-fixed-dim": "#48d4f3",
        "on-secondary-fixed": "#003a45",
        "on-tertiary-fixed-variant": "#740044",
        "inverse-on-surface": "#52555c",
        "on-secondary": "#004b58",
        "on-tertiary-fixed": "#37001d",
        "on-background": "#4a2c6d",
        "primary-fixed": "#b28cff",
        "tertiary-dim": "#ff67ad",
        "error-container": "#a70138",
        "surface-container-highest": "#ffe0ef",
        "surface-container-lowest": "#ffffff"
      },
      fontFamily: {
        "headline": ["Manrope"],
        "body": ["Inter"],
        "label": ["Inter"]
      },
      borderRadius: {
        "DEFAULT": "1rem",
        "lg": "2rem",
        "xl": "3rem",
        "full": "9999px"
      },
    },
  },
  plugins: [],
}
